export const SCAN_RESULTS = {
  AUTHENTIC: 'AUTHENTIC',
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_SOLD: 'ALREADY_SOLD'
};

export const SCAN_RESULT_MESSAGES = {
  [SCAN_RESULTS.AUTHENTIC]: '✅ AUTHENTIC PRODUCT',
  [SCAN_RESULTS.NOT_FOUND]: '⚠️ COUNTERFEIT DETECTED',
  [SCAN_RESULTS.ALREADY_SOLD]: '⚠️ WARNING: Already Sold'
};